// Applies prices-2026-09.mjs in two places at once:
//
//   1. the a*.mjs sources, so regenerating the article SQL keeps the fixes;
//   2. content-updates/blog-price-update-2026-09.sql, a surgical patch for the
//      rows already in the database.
//
// It has to be surgical. blog-0*.sql re-inserts body_en ON CONFLICT DO UPDATE,
// so re-running it would delete every <figure> that fill-post-images.ts wrote
// into those rows. replace() touches only the sentences named here.
//
// Nothing is written unless every single old string is found exactly once, in
// the file and, by construction, in the live row. A patch that silently matched
// nothing is the failure mode worth designing against: it would leave a FILL IN
// on a published page while reporting success.

import { readFileSync, writeFileSync } from "node:fs";
import patches from "./prices-2026-09.mjs";

const DIR = "/home/user/iluxuryegypt-latest-june12/content-updates/blog-generator";
const OUT = "/home/user/iluxuryegypt-latest-june12/content-updates/blog-price-update-2026-09.sql";
const FILES = { a1: "abu-simbel-tour-from-aswan", a2: "grand-egyptian-museum-tour",
                a3: "tombs-in-the-valley-of-kings", a4: "what-to-see-in-luxor",
                a5: "dahshur-pyramids-egypt" };

const problems = [];
const sqlSteps = [];
const rows = [];

for (const [file, slug] of Object.entries(FILES)) {
  const patch = patches[slug];
  if (!patch) { problems.push(`${slug}: no patch entry`); continue; }
  const path = `${DIR}/${file}.mjs`;
  let src = readFileSync(path, "utf8");
  let applied = 0;

  for (const [oldText, newText] of patch.body) {
    // A template literal cannot carry an unescaped backtick or ${, and neither
    // can a dollar quoted SQL literal carry its own delimiter.
    if (/[`]|\$\{/.test(newText)) { problems.push(`${slug}: replacement contains a backtick or \${`); continue; }
    if (newText.includes("$h$")) { problems.push(`${slug}: replacement contains the SQL quote delimiter`); continue; }
    if (/[–—]/.test(newText)) { problems.push(`${slug}: replacement contains an em or en dash`); continue; }

    const n = src.split(oldText).length - 1;
    if (n !== 1) { problems.push(`${slug}: body pattern found ${n} times, want exactly 1: "${oldText.slice(0, 70)}"`); continue; }
    src = src.replace(oldText, newText);
    sqlSteps.push({ slug, kind: "body", oldText, newText });
    applied++;
  }

  for (const [question, newAnswer] of patch.faqs) {
    if (/[–—]/.test(newAnswer)) { problems.push(`${slug}: FAQ replacement contains an em or en dash`); continue; }
    const wc = newAnswer.trim().split(/\s+/).length;
    if (wc < 40 || wc > 80) problems.push(`${slug}: FAQ answer for "${question.slice(0, 40)}" is ${wc} words (want 40-80)`);
    if (!/\d/.test(newAnswer)) problems.push(`${slug}: FAQ answer for "${question.slice(0, 40)}" has no number`);
    if (!src.includes(question)) { problems.push(`${slug}: FAQ question not found: "${question}"`); continue; }

    // The answer sits on the line after its question in every a*.mjs file.
    const lines = src.split("\n");
    const qi = lines.findIndex((l) => l.includes(question));
    const ai = lines.findIndex((l, i) => i > qi && /^\s*a: "/.test(l));
    if (ai === -1 || ai !== qi + 1) { problems.push(`${slug}: could not locate the answer line for "${question.slice(0, 40)}"`); continue; }
    const oldAnswer = lines[ai].replace(/^\s*a: "/, "").replace(/" \},?\s*$/, "");
    lines[ai] = `      a: ${JSON.stringify(newAnswer)} },`;
    src = lines.join("\n");
    sqlSteps.push({ slug, kind: "faq", question, oldAnswer, newAnswer });
    applied++;
  }

  if (problems.length === 0) writeFileSync(path, src);
  rows.push({ file, slug, applied });
}

if (problems.length) {
  console.error("REFUSING TO WRITE. Nothing was changed.\n");
  for (const p of problems) console.error("  " + p);
  process.exit(1);
}

console.log("file  slug                            patches");
for (const r of rows) console.log(r.file.padEnd(6), r.slug.padEnd(32), String(r.applied).padStart(3));
console.log(`\n${rows.reduce((a, r) => a + r.applied, 0)} patches written into the a*.mjs sources.`);

// ---------------------------------------------------------------- SQL patch
const q = (s) => `$h$${s}$h$`;
const bySlug = {};
for (const s of sqlSteps) (bySlug[s.slug] ??= []).push(s);

let sql = `-- Prices, opening hours and three factual corrections, September 2026.
-- Generated by content-updates/blog-generator/apply-patches.mjs. Do not hand edit.
--
-- SURGICAL ON PURPOSE. blog-0*.sql re-inserts body_en ON CONFLICT DO UPDATE,
-- so re-running those files would wipe every <figure> that fill-post-images.ts
-- has written into these rows. This patch replaces named sentences instead.
--
-- Corrections, in order of how wrong they were:
--   1. Nefertari (QV66) was listed among the Valley of the Kings add-on tickets.
--      She is in the Valley of the Queens, a separate site with its own ticket.
--   2. Ramesses VI (KV9) was recommended as one of the three tombs on the
--      general ticket. It carries its own 220 EGP charge and cannot be picked
--      at the gate. Thutmose III (KV34) takes that slot.
--   3. abu-simbel-tour-from-aswan carried an unreplaced {{RELATED_POST_SLUG}}
--      token that would have published as a literal broken link.
--
-- Run it as written. The verification block prints before COMMIT; if any row of
-- it reads anything other than 0 bad, ROLLBACK instead.

BEGIN;

CREATE TEMP TABLE _before AS
SELECT slug,
       (length(body_en) - length(replace(body_en, '<figure', ''))) / 7 AS figures,
       length(body_en) AS body_len
FROM posts
WHERE slug IN (${Object.keys(bySlug).map((s) => `'${s}'`).join(", ")});

`;

for (const [slug, steps] of Object.entries(bySlug)) {
  sql += `-- ${"-".repeat(70)}\n-- ${slug}\n\n`;
  for (const step of steps) {
    if (step.kind === "body") {
      sql += `UPDATE posts SET body_en = replace(body_en, ${q(step.oldText)}, ${q(step.newText)})\nWHERE slug = '${slug}' AND position(${q(step.oldText)} in body_en) > 0;\n\n`;
    } else {
      sql += `UPDATE posts SET faqs = (\n  SELECT jsonb_agg(CASE WHEN f->>'question' = ${q(step.question)}\n                        THEN jsonb_set(f, '{answer}', to_jsonb(${q(step.newAnswer)}::text))\n                        ELSE f END ORDER BY ord)\n  FROM jsonb_array_elements(posts.faqs) WITH ORDINALITY AS t(f, ord)\n)\nWHERE slug = '${slug}';\n\n`;
    }
  }
}

const bodyOlds = sqlSteps.filter((s) => s.kind === "body");
const faqSteps = sqlSteps.filter((s) => s.kind === "faq");

// Two of the patches append to what is already there rather than replacing it,
// so their old text is still present afterwards by design. Checking those would
// report a failure on a correct run, which is worse than not checking them: the
// signal that matters is the ones that are supposed to disappear.
const replacedOlds = bodyOlds.filter((s) => !s.newText.includes(s.oldText));

sql += `-- ${"-".repeat(70)}
-- Verification. Every "bad" column must read 0.

SELECT 'old text still present' AS check, count(*) AS bad FROM (
${replacedOlds.map((s) => `  SELECT 1 FROM posts WHERE slug = '${s.slug}' AND position(${q(s.oldText)} in body_en) > 0`).join("\n  UNION ALL\n")}
) x;

SELECT 'new text missing' AS check, count(*) AS bad FROM (
${bodyOlds.map((s) => `  SELECT 1 FROM posts WHERE slug = '${s.slug}' AND position(${q(s.newText)} in body_en) = 0`).join("\n  UNION ALL\n")}
) x;

SELECT 'old FAQ answer still present' AS check, count(*) AS bad
FROM posts p, jsonb_array_elements(p.faqs) f
WHERE f->>'answer' IN (${faqSteps.map((s) => q(s.oldAnswer)).join(", ")});

SELECT 'new FAQ answer missing' AS check, count(*) AS bad FROM (
${faqSteps.map((s) => `  SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM posts p, jsonb_array_elements(p.faqs) f WHERE p.slug = '${s.slug}' AND f->>'answer' = ${q(s.newAnswer)})`).join("\n  UNION ALL\n")}
) x;

SELECT 'FILL IN placeholder left in body' AS check, count(*) AS bad
FROM posts WHERE slug IN (${Object.keys(bySlug).map((s) => `'${s}'`).join(", ")})
  AND (body_en LIKE '%data-placeholder%' OR body_en LIKE '%FILL IN%');

SELECT 'unreplaced template token left in body' AS check, count(*) AS bad
FROM posts WHERE slug IN (${Object.keys(bySlug).map((s) => `'${s}'`).join(", ")})
  AND body_en LIKE '%{{%';

SELECT 'em or en dash in body or FAQs' AS check, count(*) AS bad
FROM posts WHERE slug IN (${Object.keys(bySlug).map((s) => `'${s}'`).join(", ")})
  AND (body_en ~ '[–—]' OR faqs::text ~ '[–—]');

SELECT 'figure lost from body' AS check, count(*) AS bad
FROM posts p JOIN _before b ON b.slug = p.slug
WHERE (length(p.body_en) - length(replace(p.body_en, '<figure', ''))) / 7 <> b.figures;

SELECT 'FAQ answer outside 40-80 words' AS check, count(*) AS bad
FROM posts p, jsonb_array_elements(p.faqs) f
WHERE p.slug IN (${Object.keys(bySlug).map((s) => `'${s}'`).join(", ")})
  AND array_length(regexp_split_to_array(trim(f->>'answer'), E'\\\\s+'), 1) NOT BETWEEN 40 AND 80;

SELECT 'Nefertari still listed as a Valley of the Kings add-on' AS check, count(*) AS bad
FROM posts WHERE slug = 'tombs-in-the-valley-of-kings'
  AND body_en LIKE '%<td>Nefertari (QV66)</td>%';

SELECT 'KV9 still recommended on the general ticket' AS check, count(*) AS bad
FROM posts WHERE slug = 'tombs-in-the-valley-of-kings'
  AND body_en LIKE '%The best value on the general ticket%';

-- What the rows look like now.
SELECT slug,
       b.figures AS figures_before,
       (length(p.body_en) - length(replace(p.body_en, '<figure', ''))) / 7 AS figures_after,
       b.body_len AS chars_before,
       length(p.body_en) AS chars_after,
       jsonb_array_length(p.faqs) AS faqs
FROM posts p JOIN _before b USING (slug)
ORDER BY slug;

COMMIT;
`;

writeFileSync(OUT, sql);
console.log(`\nWrote ${OUT}`);
console.log(`  ${bodyOlds.length} body replacements, ${faqSteps.length} FAQ answers, ${sql.split("\n").length} lines.`);
