-- Replaces the cairo destination's attractions array with a curated list
-- of 16 genuine archaeological and historical sites in Cairo and Giza only
-- (drops the earlier v1 list's residential/leisure entries: Zamalek Island,
-- Al-Azhar Park, Nile Corniche, Cairo Tower, and the El-Moez night-walk
-- duplicate). Adds the Solar Boat Museum, not present in v1.
--
-- Every description was rewritten to avoid em dashes and hyphen-as-
-- separator punctuation entirely (plain sentences/commas instead), and
-- every id below is a freshly generated UUID rather than the old a1..a25
-- style ids from v1.
--
-- Supersedes content-updates/update-cairo-destination.sql's attractions
-- section for the cairo row; that file's description/seo_title/
-- meta_description/focus_keyword/faqs fields are untouched here.
--
-- Run with: psql "$DATABASE_URL" -f content-updates/update-cairo-attractions-v2.sql

BEGIN;

UPDATE destinations SET
  attractions = $attr$[
    {"id": "b6bf44ac-d047-4964-9290-689e8f7d7d4a", "name": "Giza Pyramids and Great Sphinx", "image": "https://iluxuryegypt.com/api/assets/uploads/296b2351-3207-420d-84d8-4a925642bc47.webp", "imageAlt": "Giza Pyramids and Great Sphinx under clear desert sky", "description": "The Giza Pyramids and Great Sphinx have guarded the desert for 4,500 years, forming the centerpiece of every luxury Cairo tour. Standing before the last surviving Wonder of the Ancient World remains one of travel's most unforgettable moments, especially with private, crowd free access at dawn."},
    {"id": "32337258-cc6e-4986-8057-0452b8ecee36", "name": "Grand Egyptian Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/8cc1ba23-71a6-4635-a217-ddda9c4a48f8.webp", "imageAlt": "Grand Egyptian Museum entrance with the colossal statue of Ramesses II", "description": "The Grand Egyptian Museum, the largest archaeological institution on Earth, unites Tutankhamun's complete treasures for the first time beneath a colossal statue of Ramesses II. It is an essential stop for anyone exploring ancient Egyptian history in Cairo."},
    {"id": "7afe7d37-38ba-40f2-85cd-24353e8b3e1d", "name": "Egyptian Museum, Tahrir", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Egyptian Museum Tahrir facade in Cairo, home to ancient artifacts", "description": "The Egyptian Museum in Cairo has guarded 120,000 ancient treasures within its Belle Epoque halls for over a century, from royal mummies to painted coffins. It remains a cornerstone of any private Cairo sightseeing itinerary."},
    {"id": "b0e484ef-99ed-45ca-97df-5d1bf4cb3bc0", "name": "Solar Boat Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/9dff839b-b0b2-43c2-b43c-f9e56900e392.webp", "imageAlt": "Ancient solar boat of King Khufu at the Giza Solar Boat Museum", "description": "The Solar Boat Museum at Giza preserves King Khufu's 4,600 year old funerary vessel, discovered dismantled beside the Great Pyramid and painstakingly reassembled. It offers rare insight into ancient Egyptian shipbuilding and royal burial rituals."},
    {"id": "4046cda1-9394-410e-b6b8-f53b0eddf19e", "name": "Saqqara Step Pyramid", "image": "https://iluxuryegypt.com/api/assets/uploads/52998ee5-4541-441c-bff2-b7ab227dc8ae.webp", "imageAlt": "Step Pyramid of Djoser at Saqqara, the world's oldest monumental stone structure", "description": "The Step Pyramid of Djoser at Saqqara, built around 2650 BC, stands as the world's oldest monumental stone structure. It served as the founding prototype for pyramid building and remains a highlight of private Cairo excursions beyond Giza."},
    {"id": "e05a5427-060e-4dcb-9d1f-57670921f20f", "name": "Memphis, Ancient Capital", "image": "https://iluxuryegypt.com/api/assets/uploads/9c25892b-596c-4273-9a3b-f30fbfd2168f.webp", "imageAlt": "Colossal statue of Ramesses II at Memphis, Egypt's ancient first capital", "description": "Memphis, Egypt's ancient first capital founded around 3100 BC, endures at Mit Rahina through a colossal recumbent Ramesses II statue and an alabaster sphinx. It offers a quieter historical stop on a Cairo day tour."},
    {"id": "5883add2-3364-4bba-b13b-17c115655574", "name": "Dahshur Bent and Red Pyramids", "image": "https://iluxuryegypt.com/api/assets/uploads/51282985-b738-4a02-80fb-252aab881835.webp", "imageAlt": "Bent Pyramid and Red Pyramid at Dahshur near Cairo", "description": "The Dahshur Pyramids reveal pyramid building's experimental dawn. The dramatically angled Bent Pyramid and the smooth sided Red Pyramid served as Egypt's first true predecessors to Giza, making them a fascinating addition to any Cairo private tour."},
    {"id": "edd5f6fa-16ab-4408-af1c-b136706090da", "name": "Citadel of Saladin", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Citadel of Saladin overlooking Cairo's medieval skyline", "description": "The Cairo Citadel, a medieval fortress built by Saladin in 1176, served as the seat of Egyptian government for nearly 700 years. This commanding hilltop landmark remains central to any historic Cairo tour itinerary."},
    {"id": "34cc21a5-48ca-416d-bf2d-18f58a23c362", "name": "Mohamed Ali Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/ad0ed541-36d8-4907-a2d4-060a46990341.webp", "imageAlt": "Mohamed Ali Alabaster Mosque domes at the Cairo Citadel", "description": "The Mohamed Ali Mosque, known as the Alabaster Mosque, crowns the Citadel with Ottoman domes and pencil minarets built between 1830 and 1848. It ranks among Islamic Cairo's most photographed architectural landmarks."},
    {"id": "b68e6e87-d1b2-4345-b6d5-0b33d5cd8025", "name": "Sultan Hassan Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/633d82bc-43bc-410f-bae4-a59465584566.webp", "imageAlt": "Sultan Hassan Mosque's monumental entrance portal in Islamic Cairo", "description": "Sultan Hassan Mosque, completed in 1363, is Mamluk architecture's supreme achievement. Its 38 meter entrance portal ranks among the tallest and most theatrical in Islamic design, making it a must see on any Islamic Cairo tour."},
    {"id": "42ec5c6b-2abd-469f-b5e9-a6ed1d0987a5", "name": "Al Rifai Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Al Rifai Mosque interior, Egypt's royal mausoleum in Cairo", "description": "Al Rifai Mosque, completed in 1912, serves as Egypt's royal mausoleum, holding King Farouk's tomb beneath a vast dome of imperial marble. It forms a striking companion stop beside Sultan Hassan on a Cairo tour."},
    {"id": "5b980a32-3c96-4330-ad11-2e6f25e85fa8", "name": "Al Azhar Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/633d82bc-43bc-410f-bae4-a59465584566.webp", "imageAlt": "Al Azhar Mosque courtyard, Sunni Islam's spiritual and academic center", "description": "Al Azhar Mosque, founded in 970 AD, remains Sunni Islam's spiritual heart and home to the oldest continuously operating university on Earth. It carries ten centuries of Cairo's religious and academic history."},
    {"id": "00ec3962-15b3-4f6d-94b2-8cffd89fd25a", "name": "Ibn Tulun Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Ibn Tulun Mosque's spiraling minaret, Cairo's oldest intact mosque", "description": "Ibn Tulun Mosque, built between 876 and 879 AD, is Cairo's oldest intact mosque. Its spiraling minaret echoes Samarra across eleven centuries and remains a serene architectural gem on any historic Cairo itinerary."},
    {"id": "00d35f06-d250-44f5-b659-4853cc39bf8d", "name": "Khan el Khalili Bazaar", "image": "https://iluxuryegypt.com/api/assets/uploads/f1a59fb7-ec63-4cf7-95a0-9684cd6d9127.webp", "imageAlt": "Khan el Khalili bazaar lanes in historic Cairo", "description": "Khan el Khalili has traded continuously since 1382. Its labyrinthine lanes of goldsmiths, spice merchants, and perfumers form one of the Arab world's most atmospheric marketplaces, essential for authentic Cairo shopping experiences."},
    {"id": "f40cb47e-6608-491d-bf5b-3cda9bf3901c", "name": "Hanging Church", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Hanging Church interior above the Roman fortress of Babylon in Cairo", "description": "The Hanging Church, suspended above the Roman fortress of Babylon since the 7th century, ranks among the world's oldest Christian sanctuaries. Its ivory inlaid altar screen makes it a highlight of any Coptic Cairo tour."},
    {"id": "ebc23026-c3ea-4ac1-b147-60a4760ee5c4", "name": "Coptic Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Coptic Museum collection of early Christian Egyptian art", "description": "The Coptic Museum holds the world's finest collection of Coptic Christian art, over 16,000 objects tracing Egypt's transformation from pharaonic legacy to Christian civilization. It is essential for understanding Coptic Cairo's deep history."}
  ]$attr$::jsonb,
  updated_at = now()
WHERE slug = 'cairo';

-- Review the output above (row count, any 0-row UPDATE means a slug
-- mismatch) before committing.
COMMIT;
