-- Full content refresh for the Aswan destination (slug: aswan): description,
-- SEO fields, a new 10-question faqs array, and a full 17-entry attractions
-- array (previously only 1 placeholder entry existed). Photos are reused
-- across several attractions pending dedicated photography for each site,
-- matched by architectural/geographic fit (temple sites -> temple photos,
-- Nile/island sites -> the Nile-view photo), the same interim approach
-- used for Cairo's and Luxor's attraction arrays. Every id is a freshly
-- generated UUID (both attractionSchema and faqSchema require one) so
-- the admin "Update Destination" button doesn't hit the missing-id
-- validation failure fixed for Cairo/Luxor in the DestinationForm.tsx
-- commit just before this one.
--
-- Run with: psql "$DATABASE_URL" -f content-updates/update-aswan-destination-full.sql

BEGIN;

UPDATE destinations SET
  description = 'Aswan sits at Egypt''s southern frontier, where pharaonic civilization once met the kingdoms of Nubia along the Nile''s calmest waters. Ancient temples, granite quarries, and a living Nubian culture define this quieter, more intimate corner of Egypt. A luxury Aswan tour reveals sites ranging from the colossal cliffside temples of Abu Simbel to the graceful island sanctuary of Philae, while colorful Nubian villages and a slow felucca sail across the Nile offer a gentler pace than Cairo or Luxor. Fewer crowds and a slower rhythm set Aswan apart from Egypt''s more visited ancient sites.',
  seo_title = 'Luxury Aswan Tours | Nubian Egypt Travel - iLuxury Egypt',
  meta_description = 'Discover Aswan''s temples and Nubian culture with a private luxury tour - Abu Simbel, Philae Temple, and a peaceful Nile felucca sail await.',
  focus_keyword = 'luxury Aswan tours',
  attractions = $attr$[
    {"id": "541985e3-7dcb-4401-aefa-d7a91c9fca19", "name": "Abu Simbel Temples", "image": "https://iluxuryegypt.com/api/assets/uploads/e7502507-3e2a-4318-8888-b270b8ddcabe.webp", "imageAlt": "Abu Simbel colossal cliff face temples above Lake Nasser", "description": "Abu Simbel, Ramesses II's supreme masterpiece, houses two colossal cliff face temples whose four seated pharaoh statues rise 20 meters above Lake Nasser. It remains the most iconic highlight of any luxury Aswan tour."},
    {"id": "2af996aa-2da6-4263-aa6b-0e19b7c6ee96", "name": "Philae Temple (Temple of Isis)", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Philae Temple colonnades on a Nile island in Aswan", "description": "The Temple of Philae, dedicated to the goddess Isis, rises from a Nile island in golden stone and still water. Its graceful colonnades rank among Egypt's most romantic ruins and a must see in Aswan."},
    {"id": "71a88016-9ee3-43db-bd38-adaedc5159b0", "name": "Kom Ombo Temple", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Kom Ombo Temple ruins beside the Nile", "description": "Kom Ombo Temple sits directly on the Nile's bank, uniquely dedicated to both Horus and Sobek. Its walls carved with rare ancient Egyptian medical instruments make it a distinctive stop on a private Aswan itinerary."},
    {"id": "8a7c3d22-d5ca-47ab-a7c1-bd4e2b095c52", "name": "Edfu Temple (Temple of Horus)", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Edfu Temple towering pylon and columns", "description": "The Temple of Edfu, the best preserved ancient monument in Egypt, offers a complete encounter with pharaonic architecture through its towering pylon, hypostyle hall, and perfectly intact sanctuary near Aswan on the Nile."},
    {"id": "897a8c1c-8469-4791-a622-b8fbfaa5ed55", "name": "Kalabsha Temple", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Kalabsha Temple ancient Nubian monument near Aswan", "description": "Kalabsha Temple, one of Nubia's largest freestanding ancient monuments, reflects centuries of cultural fusion through reliefs of Roman emperors in pharaonic costume, offering a unique addition to any private Aswan tour itinerary."},
    {"id": "5fff809c-573f-4984-bb2d-02f10e0207d7", "name": "Aswan High Dam", "image": "https://iluxuryegypt.com/api/assets/uploads/0594154f-e9bd-4545-a19e-17efefb33794.webp", "imageAlt": "Aswan High Dam aerial view across the Nile canyon", "description": "The Aswan High Dam, completed in 1971, transformed Egypt's relationship with the Nile and created Lake Nasser. It stands as one of the 20th century's great engineering feats and a notable Aswan landmark."},
    {"id": "e2394201-4c72-448e-9704-93ba8d8fc673", "name": "Unfinished Obelisk", "image": "https://iluxuryegypt.com/api/assets/uploads/8cc1ba23-71a6-4635-a217-ddda9c4a48f8.webp", "imageAlt": "Unfinished Obelisk lying in Aswan's ancient granite quarry", "description": "The Unfinished Obelisk lies exactly as ancient workers abandoned it in Aswan's granite quarries. Its 42 meter length reveals pharaonic stone carving methods in vivid detail, unique among Aswan's historic sites."},
    {"id": "5e51194c-7e3b-408b-b75b-170d59567ce2", "name": "Nubian Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Nubian Museum artifacts and exhibits in Aswan", "description": "The Nubian Museum in Aswan traces over 50,000 years of Nubian civilization, preserving artifacts rescued from ancient sites flooded by Lake Nasser, an essential stop for understanding Aswan's rich cultural heritage."},
    {"id": "c94dc936-374e-4fa3-8869-fac99cacaa34", "name": "Elephantine Island", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Elephantine Island ruins and Nile views in Aswan", "description": "Elephantine Island, one of Egypt's oldest continuously inhabited sites, served as the pharaonic state's southern frontier and cult center of the ram headed god Khnum, a key stop on an Aswan Nile excursion."},
    {"id": "763acc5a-432d-4b03-93db-c3e29c43e45d", "name": "Kitchener's Island (Botanical Garden)", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Kitchener's Island botanical garden along the Nile in Aswan", "description": "Kitchener's Island in Aswan, a lush Nile botanical garden given to Lord Kitchener in the 1890s, holds exotic plants gathered from across Africa, Asia, and the Far East, a peaceful contrast to Aswan's ancient sites."},
    {"id": "81aaed79-7daa-4da8-83eb-41622be8e66e", "name": "First Cataract", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "First Cataract rocky Nile landscape in Aswan", "description": "The First Cataract at Aswan marked ancient Egypt's southern boundary. Its rushing water and granite boulders form the region's most atmospheric natural landscape and a scenic highlight of any Aswan tour."},
    {"id": "0097aeee-59c1-4306-bba8-30d5485966ea", "name": "West Bank Tombs (Nobles' Tombs)", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Nobles' Tombs carved into the hillside in Aswan", "description": "The Aswan Nobles' Tombs, cut into the west bank's golden hillside, hold some of Egypt's oldest painted burial interiors alongside the ruined Monastery of St. Simeon, rewarding closer exploration on an Aswan itinerary."},
    {"id": "e8cefaae-0eb9-4812-92d0-3c2d03516a3e", "name": "Nubian Villages", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Colorful Nubian village houses near Aswan", "description": "Nubian Villages near Aswan display brightly painted mudbrick houses in vivid blues and yellows, reflecting one of Africa's oldest surviving cultures along the Nile and a colorful highlight of any Aswan tour."},
    {"id": "89668202-9997-4cfa-be83-b44093cacd74", "name": "Wadi el-Seboua", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Wadi el Seboua temple and sphinx avenue near Lake Nasser", "description": "Wadi el Seboua, the Valley of the Lions, guards its Ramesses II temple with an avenue of sphinx statues on the remote shores of Lake Nasser, a lesser visited treasure for dedicated Aswan travelers."},
    {"id": "6135c450-e267-4064-b6b3-d8926467bc08", "name": "Nilometer of Elephantine", "image": "https://iluxuryegypt.com/api/assets/uploads/33674831-d5bb-4a6f-bad5-4f77acc5b492.webp", "imageAlt": "Ancient Nilometer stone steps at Elephantine Island", "description": "The Nilometer of Elephantine, an ancient stone gauge cut into the riverbank, measured the Nile's annual flood levels to guide harvest planning across pharaonic Egypt, a fascinating engineering relic in Aswan."},
    {"id": "161317a5-e93f-43a1-a4ba-8318eebf1a76", "name": "Monastery of St. Simeon", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Monastery of St. Simeon ruins in the Aswan desert", "description": "The Monastery of St. Simeon, rising in magnificent ruin from Aswan's desert floor, ranks among the finest surviving examples of early Coptic Christian architecture and a striking desert excursion from Aswan."},
    {"id": "e32ca2a4-f8ef-42df-a9af-523c52665952", "name": "Fatimid Cemetery", "image": "https://iluxuryegypt.com/api/assets/uploads/713f8237-e5b5-4c13-aef1-235a0ebcadea.webp", "imageAlt": "Fatimid Cemetery beehive domed tombs in Aswan", "description": "The Fatimid Cemetery in Aswan preserves rows of mudbrick beehive domed tombs dating to the 9th and 10th centuries, among Egypt's earliest surviving Islamic funerary monuments and a quiet historic stop in Aswan."}
  ]$attr$::jsonb,
  faqs = $faqs$[
    {"id": "264890ea-4ed9-466e-8191-21cc0856ee0f", "question": "How far is Abu Simbel from Aswan city?", "answer": "Abu Simbel sits roughly three hours by road from Aswan, though many travelers opt for a short domestic flight to save time while still experiencing Ramesses II's colossal cliffside temples."},
    {"id": "27a09bf6-6225-4b38-b4b8-2e87108fb678", "question": "What is the difference between Philae Temple and Abu Simbel?", "answer": "Philae is a graceful island sanctuary dedicated to the goddess Isis near central Aswan, while Abu Simbel is a monumental cliffside complex built by Ramesses II much farther south."},
    {"id": "b2d3cd7d-cf4c-4b28-8482-f2c06d685757", "question": "Can I visit Kom Ombo and Edfu on the way to Luxor?", "answer": "Yes, both temples sit along the Nile between Aswan and Luxor, making them natural stops on a private felucca sail or Nile cruise heading north."},
    {"id": "f252c2a8-95e2-4fa9-ae22-97b2c1965007", "question": "Is a felucca ride in Aswan worth doing?", "answer": "Yes, a felucca sail around Elephantine Island offers one of the most peaceful ways to experience the Nile, with clearer water and quieter surroundings than anywhere else in Egypt."},
    {"id": "04afd954-92fa-41ac-bf10-9e0f4ba98546", "question": "What is the Nubian Museum and why should I visit?", "answer": "The Nubian Museum traces over 50,000 years of Nubian civilization, preserving artifacts rescued from ancient sites before they were flooded by Lake Nasser, offering essential cultural context for Aswan."},
    {"id": "5afe53de-1c56-49d1-a576-6bfb103990ce", "question": "How was Philae Temple saved from flooding?", "answer": "Philae Temple was carefully dismantled and relocated to nearby Agilkia Island in a major UNESCO rescue project after the Aswan High Dam raised Nile water levels."},
    {"id": "bd5a5307-5af1-460b-b78a-3c0da5a9daf5", "question": "Are Nubian villages open to visitors?", "answer": "Yes, several Nubian villages near Aswan welcome visitors to experience brightly painted mudbrick houses and one of Africa's oldest surviving cultures firsthand."},
    {"id": "1919a836-a1df-4152-820a-033e0bc43a5a", "question": "What is the Unfinished Obelisk?", "answer": "The Unfinished Obelisk lies exactly as ancient workers abandoned it in Aswan's granite quarries, offering rare insight into how the ancient Egyptians carved and transported massive stone monuments."},
    {"id": "c00ed7fb-589f-4d7a-b8b9-a6c6e85fdadf", "question": "What is the best time of year to visit Aswan?", "answer": "Winter months from November through February bring the most comfortable temperatures, since Aswan is one of the hottest cities in Egypt during summer."},
    {"id": "b1733f46-a328-4144-9d5b-078ea244e33c", "question": "Can Aswan be visited as part of a longer Nile cruise?", "answer": "Yes, Aswan typically marks the southern endpoint of a private Nile cruise that begins in Luxor, passing Edfu and Kom Ombo along the way."}
  ]$faqs$::jsonb,
  updated_at = now()
WHERE slug = 'aswan';

-- Review the output above (row count, any 0-row UPDATE means a slug
-- mismatch) before committing.
COMMIT;
