-- Full content refresh for the Cairo destination (slug: cairo):
-- description, SEO fields (seo_title, meta_description, focus_keyword),
-- a new 10-question faqs array, and a full replacement of the attractions
-- array with 25 fully-populated entries (id, name, image, imageAlt,
-- description). attractions is replaced wholesale rather than patched
-- element-by-element, since the array's prior length/order isn't assumed.
--
-- Note: attractions #16-20 (the five Coptic Cairo sites) intentionally
-- share one placeholder image per the source brief, pending real photos.
-- A few other entries also intentionally reuse the same image across
-- related sites (e.g. the Citadel photo for #7/#10/#14, the Al-Azhar Park
-- skyline photo for #21-24) — these repeats were explicit in the brief,
-- not an oversight here.
--
-- Run with: psql "$DATABASE_URL" -f content-updates/update-cairo-destination.sql

BEGIN;

UPDATE destinations SET
  description = 'Cairo is Egypt''s ancient capital, where the last surviving pyramid of the ancient world rises beside a city layered with five thousand years of continuous history. Medieval mosques, Coptic churches, and the treasures of the pharaohs coexist within a single sprawling metropolis, making it the essential starting point for any luxury Cairo tour. Beyond the Giza Plateau, the city holds Islamic Cairo''s medieval skyline, the newly opened Grand Egyptian Museum, and centuries-old markets still trading as they did in the fourteenth century. Few cities on Earth compress this much civilization into one skyline — and few reward a private, expertly guided visit as richly as Cairo does.',
  seo_title = 'Luxury Cairo Tours | Private Egypt Travel – iLuxury Egypt',
  meta_description = 'Discover Cairo''s pyramids, museums, and medieval quarters with a private luxury tour — expert Egyptologists, five-star access, and journeys built around you.',
  focus_keyword = 'luxury Cairo tours',
  faqs = $faqs$[
    {"question": "What is the best way to see the Pyramids of Giza privately?", "answer": "A private guided tour with an expert Egyptologist and dedicated vehicle lets you skip public queues, explore at your own pace, and access areas like the Solar Boat Museum without the crowds that gather at the main viewing points."},
    {"question": "How many days do you need in Cairo to see the main sites?", "answer": "Three to four days allow time for Giza, Saqqara, and Dahshur, the Grand Egyptian Museum, and Islamic Cairo's mosques and markets — enough to see Cairo's highlights without rushing between sites."},
    {"question": "Is the Grand Egyptian Museum open to visitors yet?", "answer": "Yes, the Grand Egyptian Museum has opened to the public, showcasing Tutankhamun's complete treasure collection together for the first time beneath a colossal statue of Ramesses II."},
    {"question": "What is the difference between the Egyptian Museum and the Grand Egyptian Museum?", "answer": "The Egyptian Museum in Tahrir holds 120,000 artifacts in its century-old Belle Époque building, while the Grand Egyptian Museum near Giza is a newer, larger institution built specifically to house Tutankhamun's full collection."},
    {"question": "Can you visit Saqqara and Dahshur in the same day as Giza?", "answer": "Yes, all three sites sit within a short drive of one another southwest of Cairo, making it possible to combine the Giza Pyramids, Saqqara's Step Pyramid, and Dahshur's Bent and Red Pyramids in a single private day tour."},
    {"question": "What is the best time of year to visit Cairo?", "answer": "October through April offers the most comfortable temperatures for exploring outdoor sites like Giza and Saqqara, while summer months bring intense heat that's best avoided for extended walking tours."},
    {"question": "Is Khan el-Khalili safe to visit at night?", "answer": "Khan el-Khalili is generally safe and especially atmospheric after dark, when lantern light and the evening crowds bring the centuries-old bazaar to life — a private guide adds both insight and ease of navigation."},
    {"question": "How do I book private access to Cairo's Islamic monuments?", "answer": "Private access to sites like the Citadel, Sultan Hassan Mosque, and Al-Muizz Street is arranged in advance through a luxury tour operator familiar with entry permits and the quietest visiting hours."},
    {"question": "What should first-time visitors to Cairo prioritize seeing?", "answer": "The Giza Pyramids and Sphinx, the Grand Egyptian Museum, and Islamic Cairo's Citadel and mosques form the essential first-time itinerary, balancing ancient history with medieval architecture."},
    {"question": "Can a Cairo private tour be combined with a Nile cruise to Luxor and Aswan?", "answer": "Yes, Cairo is the natural starting point for a longer Egypt itinerary that continues south to a private Nile cruise between Luxor and Aswan, combining the capital with Egypt's ancient temple sites."}
  ]$faqs$::jsonb,
  attractions = $attr$[
    {"id": "a1", "name": "Giza Pyramids & Great Sphinx", "image": "https://iluxuryegypt.com/api/assets/uploads/296b2351-3207-420d-84d8-4a925642bc47.webp", "imageAlt": "Giza Pyramids and Great Sphinx under clear desert sky", "description": "The Giza Pyramids and Great Sphinx have guarded the desert for 4,500 years, forming the centerpiece of every luxury Cairo tour. Standing before the last surviving Wonder of the Ancient World remains one of travel's most unforgettable moments, especially with private, crowd-free access at dawn."},
    {"id": "a2", "name": "Grand Egyptian Museum (GEM)", "image": "https://iluxuryegypt.com/api/assets/uploads/8cc1ba23-71a6-4635-a217-ddda9c4a48f8.webp", "imageAlt": "Grand Egyptian Museum entrance with the colossal statue of Ramesses II", "description": "The Grand Egyptian Museum, the largest archaeological institution on Earth, unites Tutankhamun's complete treasures for the first time beneath a colossal statue of Ramesses II — an essential stop for anyone exploring ancient Egyptian history in Cairo."},
    {"id": "a3", "name": "Egyptian Museum (Tahrir)", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Egyptian Museum Tahrir facade in Cairo, home to 120,000 ancient artifacts", "description": "The Egyptian Museum in Cairo has guarded 120,000 ancient treasures within its Belle Époque halls for over a century, from royal mummies to painted coffins, remaining a cornerstone of any private Cairo sightseeing itinerary."},
    {"id": "a4", "name": "Saqqara & Step Pyramid", "image": "https://iluxuryegypt.com/api/assets/uploads/52998ee5-4541-441c-bff2-b7ab227dc8ae.webp", "imageAlt": "Step Pyramid of Djoser at Saqqara, the world's oldest monumental stone structure", "description": "The Step Pyramid of Djoser at Saqqara, built around 2650 BC, stands as the world's oldest monumental stone structure — the founding prototype for pyramid building and a highlight of private Cairo excursions beyond Giza."},
    {"id": "a5", "name": "Memphis (Mit Rahina)", "image": "https://iluxuryegypt.com/api/assets/uploads/9c25892b-596c-4273-9a3b-f30fbfd2168f.webp", "imageAlt": "Colossal statue of Ramesses II at Memphis, Egypt's ancient first capital", "description": "Memphis, Egypt's ancient first capital founded around 3100 BC, endures at Mit Rahina through a colossal recumbent Ramesses II statue and an alabaster sphinx, offering a quieter historical stop on a Cairo day tour."},
    {"id": "a6", "name": "Dahshur Pyramids", "image": "https://iluxuryegypt.com/api/assets/uploads/51282985-b738-4a02-80fb-252aab881835.webp", "imageAlt": "Bent Pyramid and Red Pyramid at Dahshur near Cairo", "description": "The Dahshur Pyramids reveal pyramid-building's experimental dawn: the dramatically angled Bent Pyramid and the smooth-sided Red Pyramid, Egypt's first true predecessor to Giza — a fascinating addition to any Cairo private tour."},
    {"id": "a7", "name": "Citadel of Saladin", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Citadel of Saladin overlooking Cairo's medieval skyline", "description": "The Cairo Citadel, a medieval fortress built by Saladin in 1176, served as the seat of Egyptian government for nearly 700 years — a commanding hilltop landmark central to any historic Cairo tour itinerary."},
    {"id": "a8", "name": "Mohamed Ali Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/ad0ed541-36d8-4907-a2d4-060a46990341.webp", "imageAlt": "Mohamed Ali Alabaster Mosque domes at the Cairo Citadel", "description": "The Mohamed Ali Mosque, known as the Alabaster Mosque, crowns the Citadel with Ottoman domes and pencil minarets built between 1830 and 1848 — one of Islamic Cairo's most photographed architectural landmarks."},
    {"id": "a9", "name": "Sultan Hassan Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/633d82bc-43bc-410f-bae4-a59465584566.webp", "imageAlt": "Sultan Hassan Mosque's monumental entrance portal in Islamic Cairo", "description": "Sultan Hassan Mosque, completed in 1363, is Mamluk architecture's supreme achievement, its 38-meter entrance portal among the tallest and most theatrical in Islamic design — a must-see on any Islamic Cairo tour."},
    {"id": "a10", "name": "Al-Rifai Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Al-Rifai Mosque interior, Egypt's royal mausoleum in Cairo", "description": "Al-Rifai Mosque, completed in 1912, serves as Egypt's royal mausoleum, holding King Farouk's tomb beneath a vast dome of imperial marble — a striking companion stop beside Sultan Hassan on a Cairo tour."},
    {"id": "a11", "name": "Khan el-Khalili Bazaar", "image": "https://iluxuryegypt.com/api/assets/uploads/f1a59fb7-ec63-4cf7-95a0-9684cd6d9127.webp", "imageAlt": "Khan el-Khalili bazaar lanes in historic Cairo", "description": "Khan el-Khalili has traded continuously since 1382, its labyrinthine lanes of goldsmiths, spice merchants, and perfumers forming one of the Arab world's most atmospheric marketplaces — essential for authentic Cairo shopping experiences."},
    {"id": "a12", "name": "Al-Muizz Street", "image": "https://iluxuryegypt.com/api/assets/uploads/b046ce77-6609-4e08-9143-5a556cf017ae.webp", "imageAlt": "Al-Muizz Street's medieval Islamic monuments in Cairo", "description": "Al-Muizz Street, built in the 10th century as the Fatimid capital's ceremonial spine, holds the highest concentration of medieval Islamic monuments found anywhere — a living open-air museum in the heart of Cairo."},
    {"id": "a13", "name": "Al-Azhar Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/633d82bc-43bc-410f-bae4-a59465584566.webp", "imageAlt": "Al-Azhar Mosque courtyard, Sunni Islam's spiritual and academic center", "description": "Al-Azhar Mosque, founded in 970 AD, remains Sunni Islam's spiritual heart and home to the oldest continuously operating university on Earth, layered across ten centuries of Cairo's religious and academic history."},
    {"id": "a14", "name": "Ibn Tulun Mosque", "image": "https://iluxuryegypt.com/api/assets/uploads/3ecbf8b6-1d34-456f-b2be-ec757f105a55.webp", "imageAlt": "Ibn Tulun Mosque's spiraling minaret, Cairo's oldest intact mosque", "description": "Ibn Tulun Mosque, built between 876 and 879 AD, is Cairo's oldest intact mosque, its spiraling minaret echoing Samarra across eleven centuries — a serene architectural gem on any historic Cairo itinerary."},
    {"id": "a15", "name": "Bab Zuweila & Fatimid Walls", "image": "https://iluxuryegypt.com/api/assets/uploads/e39c2ffc-432b-4768-8355-7fcc55a108b4.webp", "imageAlt": "Bab Zuweila gate and Fatimid city walls in Islamic Cairo", "description": "Bab Zuweila, a double-towered Fatimid gateway raised in 1092, survives as one of medieval Cairo's three great gates alongside the city's best-preserved ancient walls — a striking stop on an Islamic Cairo walking tour."},
    {"id": "a16", "name": "Hanging Church (St. Virgin Mary)", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Hanging Church interior above the Roman fortress of Babylon in Cairo", "description": "The Hanging Church, suspended above the Roman fortress of Babylon since the 7th century, ranks among the world's oldest Christian sanctuaries with its ivory-inlaid altar screen — a highlight of any Coptic Cairo tour."},
    {"id": "a17", "name": "Coptic Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Coptic Museum collection of early Christian Egyptian art", "description": "The Coptic Museum holds the world's finest collection of Coptic Christian art, over 16,000 objects tracing Egypt's transformation from pharaonic legacy to Christian civilization — essential for understanding Coptic Cairo's deep history."},
    {"id": "a18", "name": "Ben Ezra Synagogue", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Ben Ezra Synagogue, one of Egypt's oldest Jewish heritage sites", "description": "Ben Ezra Synagogue, among Egypt's oldest Jewish sites, gained scholarly fame in 1896 when 300,000 medieval manuscripts were discovered hidden within its historic attic — a fascinating stop on a Coptic Cairo tour."},
    {"id": "a19", "name": "Abu Serga Church (St. Sergius)", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Abu Serga Church, traditional resting place of the Holy Family in Cairo", "description": "Abu Serga Church, built in the 4th or 5th century AD, marks the traditional resting place of the Holy Family and ranks among Coptic Christianity's most sacred sites — central to Coptic Cairo pilgrimage tours."},
    {"id": "a20", "name": "Church of St. Barbara", "image": "https://iluxuryegypt.com/api/assets/uploads/dfd0784b-e78d-49b8-b07d-8476ef3a3651.webp", "imageAlt": "Church of St. Barbara's triple-apsed sanctuary in Coptic Cairo", "description": "The Church of St. Barbara, raised in the late 7th century, preserves one of Cairo's finest triple-apsed sanctuaries alongside a rare collection of ancient Coptic icons — a quiet gem within Coptic Cairo."},
    {"id": "a21", "name": "Al-Azhar Park", "image": "https://iluxuryegypt.com/api/assets/uploads/b80b1d83-d006-441a-8962-a405e8e68150.webp", "imageAlt": "Al-Azhar Park skyline view over historic Cairo", "description": "Al-Azhar Park, a 30-hectare garden opened in 2005 atop five centuries of buried refuse, crowns a hilltop offering historic Cairo's most sweeping panoramic skyline — perfect for sunset views on a Cairo tour."},
    {"id": "a22", "name": "Zamalek Island", "image": "https://iluxuryegypt.com/api/assets/uploads/b80b1d83-d006-441a-8962-a405e8e68150.webp", "imageAlt": "Zamalek Island's tree-lined streets and Nile views in Cairo", "description": "Zamalek, a leafy Nile island lined with villas and embassies, has embodied Cairo's cosmopolitan refinement for over a century through its galleries, cafes, and tree-shaded streets — a relaxed contrast on a luxury Cairo tour."},
    {"id": "a23", "name": "Nile Corniche", "image": "https://iluxuryegypt.com/api/assets/uploads/b80b1d83-d006-441a-8962-a405e8e68150.webp", "imageAlt": "Nile Corniche at sunset with Cairo's skyline reflected on the water", "description": "The Nile Corniche, Cairo's grand riverside boulevard, turns gold at sunset as the city's towers glow against the water — one of Africa's most atmospheric promenades and a scenic close to any Cairo day tour."},
    {"id": "a24", "name": "Cairo Tower", "image": "https://iluxuryegypt.com/api/assets/uploads/b80b1d83-d006-441a-8962-a405e8e68150.webp", "imageAlt": "Cairo Tower's lotus-inspired lattice rising above Gezira Island", "description": "Cairo Tower, rising 187 meters above Gezira Island, stands as Africa's tallest structure north of the equator, its lotus-inspired lattice built between 1956 and 1961 — offering panoramic views on any Cairo sightseeing tour."},
    {"id": "a25", "name": "El-Moez District Night Walk", "image": "https://iluxuryegypt.com/api/assets/uploads/f1a59fb7-ec63-4cf7-95a0-9684cd6d9127.webp", "imageAlt": "Al-Muizz Street illuminated by lanterns during a Cairo night walk", "description": "Al-Muizz Street at night transforms into Islamic Cairo's most theatrical scene, when golden lantern light and drifting shisha smoke animate the medieval lanes near Khan el-Khalili — an unforgettable evening Cairo tour experience."}
  ]$attr$::jsonb,
  updated_at = now()
WHERE slug = 'cairo';

-- Review the output above (row count, any 0-row UPDATE means a slug
-- mismatch) before committing.
COMMIT;
