-- Full replacement of the luxor destination's attractions array with 18
-- entries: the 3 sites that already have real, distinct photos (Karnak,
-- Luxor Temple, Hatshepsut Temple) plus 15 more Luxor/Theban-west-bank
-- sites that don't have dedicated photos yet, temporarily mapped onto
-- the Karnak and Hatshepsut photos by architectural/geographic fit
-- (columned temples -> Karnak; open west-bank sites -> Hatshepsut) --
-- the same interim approach used for Cairo's Coptic sites, pending real
-- photos for each. Every id below is a freshly generated UUID.
--
-- Run with: psql "$DATABASE_URL" -f content-updates/update-luxor-attractions-v2.sql

BEGIN;

UPDATE destinations SET
  attractions = $attr$[
    {"id": "88e4aeb4-cf5a-4d16-b901-50afca90c9fe", "name": "Karnak Temple Complex", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Karnak Temple's ancient columned hall under a bright blue sky in Luxor", "description": "Karnak Temple, the largest religious site ever built, took over 2,000 years and 30 pharaohs to construct. Its Great Hypostyle Hall raises 134 columns skyward, making it an essential stop on any luxury Luxor tour."},
    {"id": "87ee2863-f6a0-411a-8609-ad3f8c8fd802", "name": "Luxor Temple", "image": "https://iluxuryegypt.com/api/assets/uploads/5d8c1711-23da-4523-a0e3-a6b3ef39420a.webp", "imageAlt": "Luxor Temple entrance with obelisk and colossal statues", "description": "Luxor Temple has stood at the heart of the city for over 3,400 years. Its soaring obelisk and Ramesses II colossi frame layers of pharaonic, Roman, and Islamic history, making it a highlight of any Luxor sightseeing itinerary."},
    {"id": "61d8483c-99da-4061-9e68-09069f8e05bd", "name": "Luxor Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Luxor Museum artifact display in an intimate curated setting", "description": "Luxor Museum, widely regarded as Egypt's finest, displays an alabaster statue of Amenhotep III and two royal mummies within an intimate, beautifully curated setting. It offers a focused counterpoint to the vast open air temples nearby."},
    {"id": "f23f6b21-c615-4152-a473-506e96be64e4", "name": "Mummification Museum", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Ancient Egyptian mummification artifacts on display in Luxor", "description": "The Mummification Museum on Luxor's Corniche traces the ancient science of embalming through preserved tools, sacred animal mummies, and centuries of ritual belief, adding cultural depth to any Luxor private tour."},
    {"id": "4dd2ab98-c611-44d4-9d4b-2aac6fda963e", "name": "Ramesseum", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Ramesseum temple ruins with fallen colossal statue in Luxor", "description": "The Ramesseum, immortalized by Shelley's poem Ozymandias, holds a colossal fallen statue of Ramesses II alongside some of ancient Egypt's finest surviving military reliefs on Luxor's west bank."},
    {"id": "1cf05203-77ff-480f-bbf1-711ae363e7d8", "name": "Medinet Habu", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Medinet Habu temple fortified gateway and reliefs in Luxor", "description": "Medinet Habu, Ramesses III's remarkably preserved mortuary temple, carries dramatic reliefs of the Sea Peoples' invasion behind a unique fortified Migdol gateway, a must see on the Luxor west bank."},
    {"id": "0b0b8303-6172-4d15-bd5d-39606f9c3e82", "name": "Colossi of Memnon", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Colossi of Memnon statues on the Theban plain in Luxor", "description": "The Colossi of Memnon, two 18 meter seated statues of Amenhotep III, have watched over the Theban plain for more than 3,300 years and remain among the most photographed landmarks on a Luxor tour."},
    {"id": "b9ad8c68-236d-4057-ad80-64c511c8bdf4", "name": "Valley of the Kings", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Valley of the Kings desert landscape and tomb entrances in Luxor", "description": "The Valley of the Kings, burial ground of Egypt's greatest pharaohs, holds 63 discovered tombs cut into desert rock across five centuries of royal history, forming the centerpiece of any Luxor private tour."},
    {"id": "71561802-3f1d-4080-9841-8b62d5d0101d", "name": "Valley of the Queens", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Valley of the Queens tomb entrances in Luxor", "description": "The Valley of the Queens, burial place of royal consorts and princes, preserves some of the most vividly painted tomb interiors in all of Egypt, offering a quieter contrast to the Valley of the Kings."},
    {"id": "45d1eba1-a8b1-4f86-9c2d-d504a56d4a85", "name": "Tombs of the Nobles", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Tombs of the Nobles painted interior in Luxor", "description": "The Tombs of the Nobles, carved into the hills of Sheikh Abd el Qurna, depict scenes of everyday life rather than royal gods and the afterlife, offering a rare human perspective on ancient Egyptian society."},
    {"id": "ec453b3a-4def-4326-9716-872c34c63ae3", "name": "Tomb of Nefertari", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Tomb of Nefertari vividly painted burial chamber in Luxor", "description": "The Tomb of Nefertari, created for Ramesses II's most beloved queen, contains the most beautifully painted burial chamber surviving from the ancient world, a bucket list stop on any luxury Luxor tour."},
    {"id": "86ad62b4-bfc1-4d91-a6b3-442b7d30dc21", "name": "Tomb of Tutankhamun", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Tomb of Tutankhamun entrance in the Valley of the Kings", "description": "The Tomb of Tutankhamun, discovered intact by Howard Carter in 1922, remains the only substantially undisturbed royal burial ever found in Egypt, drawing visitors from around the world to the Valley of the Kings."},
    {"id": "47103988-6761-4bcb-9bc0-8c63422d2b66", "name": "Howard Carter's House", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Howard Carter's restored house near the Valley of the Kings in Luxor", "description": "Howard Carter's House, the excavator's restored mudbrick residence near the Valley of the Kings, preserves period photographs and equipment from his historic 1922 discovery of Tutankhamun's tomb."},
    {"id": "a6e93266-e410-4be5-8ba2-1750ad4e20d6", "name": "Gurna Village", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Old Gurna village painted mudbrick facades in Luxor", "description": "Old Gurna, built directly above the Nobles' Tombs, reveals painted mudbrick facades depicting Hajj journeys in vivid traditional Egyptian folk art, a colorful cultural detour on Luxor's west bank."},
    {"id": "069b720c-471c-4001-b79a-00e9e5d42783", "name": "Malkata Palace", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Malkata Palace ruins on Luxor's west bank", "description": "Malkata Palace, built by Amenhotep III as a vast royal city on Luxor's west bank, once housed festival halls, private apartments, and an artificial harbor linked to the Nile, revealing royal life beyond the temples."},
    {"id": "e9ba8bfd-5b1c-4756-ba5f-899e0c5bf8a1", "name": "Deir el-Medina", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Deir el Medina ancient workers village ruins in Luxor", "description": "Deir el Medina, the ancient village of royal tomb builders, preserves artisans' houses, chapels, and vividly painted tombs revealing daily life during Egypt's New Kingdom period, a hidden gem for history focused travelers."},
    {"id": "15561e35-4433-49be-b1f8-12a389af565a", "name": "Temple of Seti I", "image": "https://iluxuryegypt.com/api/assets/uploads/957e080e-b0c1-4a40-8db8-49b317460747.webp", "imageAlt": "Temple of Seti I carved reliefs in Luxor", "description": "The Temple of Seti I at Qurna, built for the pharaoh's mortuary cult, preserves finely carved reliefs completed by his son Ramesses II after Seti's death in 1279 BC, a lesser visited treasure on the west bank."},
    {"id": "51729a27-f848-4f34-aed1-96a1f1171126", "name": "Mortuary Temple of Hatshepsut", "image": "https://iluxuryegypt.com/api/assets/uploads/179e2e5e-fd76-447b-843d-7a9a187c43ec.webp", "imageAlt": "Hatshepsut Temple's three colonnaded terraces in Luxor", "description": "Hatshepsut Temple rises in three colonnaded terraces from the Theban cliffs, its vivid reliefs depicting the ancient expedition to the Land of Punt, standing as one of ancient Egypt's most striking architectural achievements."}
  ]$attr$::jsonb,
  updated_at = now()
WHERE slug = 'luxor';

-- Review the output above (row count, any 0-row UPDATE means a slug
-- mismatch) before committing.
COMMIT;
