/**
 * Regenerates server/brochure/fonts.ts, which holds the two brochure faces as
 * base64 woff2 inside a stylesheet string.
 *
 * The fonts are embedded rather than linked because Puppeteer races a live
 * font request: setContent resolves on networkidle0, the @font-face fetch may
 * still be in flight, and the PDF prints in a fallback face with no error and
 * no visible failure until somebody opens the file. A data URI cannot race
 * anything.
 *
 * Only the `latin` subset is kept. The full set is 33 @font-face blocks per
 * request and most of them are Cyrillic and Vietnamese ranges this brochure
 * will never use.
 *
 *   npx tsx scripts/build-brochure-fonts.ts
 */
import fs from "fs";
import path from "path";

const URL =
  "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Inter:wght@300;400;600&display=swap";
// Google serves woff2 only to browsers it recognises. A default fetch UA gets
// a TTF stylesheet back, which is four times the size and prints identically.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

async function main() {
  const css = await (await fetch(URL, { headers: { "User-Agent": UA } })).text();

  // The `latin` subset is the one block per family whose range opens at
  // U+0000-00FF. Matched on the range rather than on the "/* latin */" comment
  // above it, because the comment is not part of the rule and a formatting
  // change upstream would silently select nothing.
  const blocks = css.split("@font-face").slice(1).map((b) => "@font-face" + b.split("}")[0] + "}");
  const latin = blocks.filter((b) => /unicode-range:\s*U\+0000-00FF/.test(b));

  if (latin.length === 0) throw new Error("no latin subset blocks found; the Google CSS format changed");

  // Both families are variable, so every requested weight of one family points
  // at the SAME woff2. Embedding per weight wrote the same 47 KB three times
  // and inflated the file by 140 KB for nothing. Group by URL and emit one
  // face per file, with a weight range spanning the weights that shared it.
  const byUrl = new Map<string, { family: string; style: string; weights: number[] }>();
  for (const block of latin) {
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? "";
    const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? "normal";
    const weight = Number(block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400");
    const entry = byUrl.get(url) ?? { family, style, weights: [] };
    entry.weights.push(weight);
    byUrl.set(url, entry);
  }

  const out: string[] = [];
  for (const [url, { family, style, weights }] of byUrl) {
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    const lo = Math.min(...weights);
    const hi = Math.max(...weights);
    const range = lo === hi ? String(lo) : `${lo} ${hi}`;
    out.push(
      `@font-face{font-family:'${family}';font-style:${style};font-weight:${range};font-display:block;` +
        `src:url(data:font/woff2;base64,${buf.toString("base64")}) format('woff2');}`
    );
    console.log(`  ${family} ${range} ${style}  ${(buf.length / 1024).toFixed(1)} KB`);
  }

  const file = `// GENERATED by scripts/build-brochure-fonts.ts. Do not edit by hand.
//
// The two brochure faces as base64 woff2, latin subset only. Embedded rather
// than linked because Puppeteer races a live font request and prints a
// fallback face with no error, which is only discovered by opening the PDF.
//
// Regenerate with: npx tsx scripts/build-brochure-fonts.ts

export const BROCHURE_FONT_CSS = ${JSON.stringify(out.join("\\n"))};
`;
  const dest = path.resolve(import.meta.dirname, "../server/brochure/fonts.ts");
  fs.writeFileSync(dest, file);
  console.log(`\nwrote ${dest} (${(file.length / 1024).toFixed(0)} KB, ${out.length} faces)`);
}

main();
