// Post-build step: inlines the critical CSS generated by
// generate-critical-css.ts into dist/public/index.html's <head>, and
// switches the full stylesheet Vite emitted to non-render-blocking —
// the same preload+media=print/onload swap pattern already used for the
// Google Fonts stylesheet in client/index.html, applied here to Vite's
// auto-injected <link rel="stylesheet"> since that one can't be hand-written
// in the source template (its hashed filename only exists after building).
import fs from "fs/promises";
import path from "path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const htmlPath = path.join(projectRoot, "dist/public/index.html");
const criticalCssPath = path.join(projectRoot, "dist/critical.css");

async function run() {
  const [html, criticalCss] = await Promise.all([
    fs.readFile(htmlPath, "utf-8"),
    fs.readFile(criticalCssPath, "utf-8"),
  ]);

  const stylesheetLinkPattern = /<link rel="stylesheet" crossorigin href="([^"]+\.css)">/;
  const match = html.match(stylesheetLinkPattern);
  if (!match) {
    throw new Error("inline-critical-css: couldn't find Vite's stylesheet <link> in dist/public/index.html");
  }
  const cssHref = match[1];

  const deferredLink =
    `<link rel="preload" as="style" href="${cssHref}" crossorigin>\n` +
    `    <link rel="stylesheet" crossorigin href="${cssHref}" media="print" onload="this.media='all'">\n` +
    `    <noscript><link rel="stylesheet" crossorigin href="${cssHref}"></noscript>`;

  let updated = html.replace(stylesheetLinkPattern, deferredLink);
  updated = updated.replace("</title>", `</title>\n    <style>${criticalCss}</style>`);

  await fs.writeFile(htmlPath, updated, "utf-8");
  console.log(`Inlined ${(Buffer.byteLength(criticalCss) / 1024).toFixed(1)}KB critical CSS and deferred ${cssHref}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
